# Generated by Django 5.0.2 on 2024-02-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='reward',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Вознаграждение'),
        ),
    ]
